all: \
  iso/music/menu.xa \
  iso/music/1.xa

# XA converts
iso/music/%.xa: iso/music/%.ogg
	tools/psxavenc/psxavenc -f 37800 -t xa -b 4 -c 2 -F 1 -C 0 $< $@
iso/music/%.xa:
	tools/xainterleave/xainterleave $@

# XA interleaves
iso/music/menu.xa: iso/music/freaky.xa iso/music/gameover.xa
iso/music/1.xa: iso/music/bite-vreen/Inst.xa iso/music/bite-vreen/Vocals.xa iso/music/restless-vreen/Inst.xa iso/music/restless-vreen/Vocals.xa